version: '3'
networks:
    nistnet:
services:
    backend:
        image: node:14.11.0-alpine
        volumes:
            - ../backend:/var/www/nistapi
        networks:
            - nistnet
        environment: 
            #Ip do host para adicionar ao whitelist do CORS da API
            - HOST_IP=10.150.0.251
        command: /bin/sh -c "cd /var/www/nistapi && npm install && node app.js"
    frontend:
        image: nginx:1.19.2-alpine
        volumes:
            - ../nginx/ssl_setup.sh:/docker-entrypoint.d/ssl_setup.sh
            - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../frontend/html:/usr/share/nginx/html
            - ../frontend/css:/data/css
            - ../frontend/js:/data/js
            - ../frontend/imgs:/data/imgs
        networks:
            - nistnet
        depends_on: 
            - backend
        ports: 
            - 80:80
