version: '3'
networks:
    nistnet:

services:
    backend:
        image: node:14.11.0-alpine
        volumes:
            - ../backend:/var/www/nistapi
        networks:
            - nistnet
        command: /bin/sh -c "cd /var/www/nistapi && node app.js"
    frontend:
        image: nginx:1.19.2-alpine
        volumes:
            - ./ssl_setup.sh:/docker-entrypoint.d/ssl_setup.sh
            #- ./default.conf:/etc/nginx/sites-enabled/default.conf
            - ../frontend/html:/usr/share/nginx/html
            - ../frontend/css:/usr/share/nginx/html/css
            - ../frontend/js:/usr/share/nginx/html/js
            - ../frontend/imgs:/usr/share/nginx/html/imgs
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        networks:
            - nistnet
        depends_on: 
            - backend
        ports: 
            - 80:8080