version: '3'
networks:
    nistnet:
services:
    nistapi:
        image: nginx:latest
        volumes:
        - ./ssl_setup.sh:/docker-entrypoint.d/setup.sh
        - ./nistapi.conf:/etc/nginx/sites-enabled/nistapi.conf
        - ../webserver:/usr/share/nginx/nistapi
        networks:
            - nistnet
        ports: 
            - 8080:8080